version: "3.9"

services:
  app:
    build: .
    container_name: projectz_app
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - projectz_network

  postgres:
    image: postgres:15
    container_name: projectz_postgres
    environment:
      POSTGRES_USER: Zeth_Ph
      POSTGRES_PASSWORD: Showmethemoney$$
      POSTGRES_DB: Zeth_photography
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - projectz_network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: projectz_cloudflared
    command: tunnel --no-autoupdate run --token <YOUR_TOKEN>
    networks:
      - projectz_network

networks:
  projectz_network:

volumes:
  pgdata:
